<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

require("template/AdminNavBar.phtml");

?>

<!DOCTYPE html>
<html>
<head>
    <link href="/css/sharedLayout.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Approve Homeowners</title>
</head>
<body>
    <main class="manage-container">
        <h2 class="page-title">Approve Homeowner Registration</h2>
    </main>
</body>
</html>


<?php
require('template/footer.phtml');
?>