<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

require("template/AdminNavBar.phtml");

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin - Generate Booking Reports</title>
    <link href="/css/sharedLayout.css" rel="stylesheet">
</head>
<body>

    <main class="manage-container">
        <h2 class="page-title">Generate Booking Reports</h2>
    </main>

</body>
</html>


<?php
require('template/footer.phtml');
?>