<?php
    require ("template/HomeownerNavBar.phtml");
?>
<html>
<head>
    <link href="/css/sharedLayout.css" rel="stylesheet">
</head>
<body>
<main class="manage-container">
    <h2 class="page-title"> Booking Request </h2>
    <table>
        <thead>
            <tr>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</main>
</body>
</html>


<?php
require ("template/footer.phtml");
?>