<?php require ('Views/template/header.phtml'); ?>

<!-- SweetAlert2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<div class="index-container" style="background: url('/images/IndexBg.png') no-repeat center center / cover">
    <div class="bg-top-layer"></div>
    <div class="index-text">
        <span id="typewriter-index" class="typewriter-text">Welcome to Power Up...</span>
        <div id="sub-text-index" class="typewriter-paragraph">
            Your network for convenient and reliable EV charging,<br>
            easily locate nearby charging stations using our interactive map,<br>
            manage your charging sessions through our user-friendly system and<br>
            enjoy a seamless charging experience every time!
        </div>
    </div>
</div>

<?php if (!empty($view->showLoginPopup)): ?>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        Swal.fire({
            title: 'Welcome!',
            text: '<?= $view->popupMessage ?>',
            icon: 'info',
            confirmButtonText: 'Got it!'
        });
    </script>
<?php endif; ?>

<?php require ('Views/template/footer.phtml'); ?>
