<?php require ('Views/template/header.phtml'); ?>
<div class="index-container" style="background: url('/images/IndexBg.png') no-repeat center center / cover">
    <div class="bg-top-layer"></div>
    <div class="index-text">
        <span id="typewriter-index" class="typewriter-text">Welcome to Power Up...</span>
        <div id="sub-text-index" class="typewriter-paragraph">
            Your network for convenient and reliable EV charging,
            easily locate nearby charging stations using our interactive map,
            manage your charging sessions through our user-friendly system and
            enjoy a seamless charging experience every time!
        </div>
    </div>
</div>

<?php require ('Views/template/footer.phtml'); ?>


