<?php

include('template/header.phtml');

?>

<head>
    <link href="/css/LoginRegCSS.css" rel="stylesheet">
</head>
<body>
  
<div class="container px-4 py-5 mx-auto">
    <div class="card card0">
        <div class="d-flex flex-lg-row flex-column-reverse">
            <div class="card card1">
                <div class="row justify-content-center my-auto">
                    <div class="col-md-8 col-10 my-5">
                 
        <div class="row justify-content-center px-3 mb-3">
                            <img id="mainLogo" src="https://i.imgur.com/PSXxjNY.png">
                        </div>
                        <h3 class="mb-5 text-center heading">We are Tidi</h3>

                        <h6 class="msg-info">Please login to your account</h6>

                        <form id="loginForm" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
                        <div class="form-group">
                            <label class="form-control-label text-muted">Username</label>
                            <input type="text" id="email" name="email" placeholder="Enter your email" class="form-control" value="<?php if (isset($_POST["email"])) {echo $_POST["email"];} ?>">
                        </div>

                        <div class="form-group">
                            <label class="form-control-label text-muted">Password</label>
                            <input type="password" id="password" name="password" placeholder="Password" class="form-control" value="<?php if (isset($_POST["password"])) {echo $_POST["password"];} ?>">
                        </div>

                        <div class="row justify-content-center my-3 px-3">
                            <button type="submit" class="btn-block btn-color">Login to Tidi</button>
                        </div>

                            <?php if (!empty($view->loginError)): ?>
                                <div class="alert alert-danger text-center">
                                    <?php echo $view->loginError; ?>
                                </div>
                            <?php endif; ?>

                    </form>
                    </div>
                </div>
                <div class="bottom text-center mb-5">
                    <p href="#" class="sm-text mx-auto mb-3">Don't have an account?<button class="btn btn-white ml-2"><a href="Signup.php">Create new</a></button></p>
                </div>
            </div>
            <div class="card card2">
                <div class="my-auto mx-md-5 px-md-5 right">
                    <h3 class="text-white">We are more than just a company</h3>
                    <small class="text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</small>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="module" src="./js/LoginFormValidation.js"></script>
<?php
include('template/footer.phtml');
?>
</body>

