<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

global $view;
require('template/header.phtml');

?>


<?php

//if (isset($_GET["updated"]) && $_GET["updated"] == "true")
//{
  //  echo "User information successfully updated!";
//}

?>


<head>
    <link href="css/ProfileCSS.css" rel="stylesheet">
</head>
<body>

<form method="POST" action="Profile.php">
<div class="container rounded bg-white mt-5 profile-container">
    <div class="row">
        <div class="col-md-4 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                <img class="rounded-circle mt-5" src="./images/profileicon.png" width="110">
                <span class="font-weight-bold"><?php echo $view->fullname; ?></span>
                <span class="text-black-50"><?php echo $view->username; ?></span>
                <span>United States</span>
            </div>
        </div>
        <div class="col-md-8">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <div class="d-flex flex-row align-items-center back">
                        <i class="fa fa-long-arrow-left mr-1 mb-1"></i>
                        <h6>Back to home</h6>
                    </div>
                    <button type="button" id="edit-profile-btn" class="btn btn-outline-success btn-sm">Edit Profile</button>
                    <!--<h6 class="text-right" id="edit-profile-btn">Edit Profile</h6>-->
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><input type="text" name="fname" class="form-control editable" placeholder="first name" value="<?php echo $view->f_Name; ?>" readonly></div>
                    <div class="col-md-6"><input type="text" name="lname" class="form-control editable" placeholder="last name" value="<?php echo $view->l_Name; ?>" readonly></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6"><input type="text" name="email" class="form-control editable" placeholder="Email" value="<?php echo $view->username; ?>" readonly></div>
                    <div class="col-md-6"><input type="text" name="phno" class="form-control editable" placeholder="Phone number" value="<?php echo $view->phone; ?>" readonly></div>
                </div>
                <!--<div class="row mt-3">
                    <div class="col-md-6"><input type="text" class="form-control editable" placeholder="address" value="<?php echo $view->l_Name; ?>"></div>
                    <div class="col-md-6"><input type="text" class="form-control editable" value="Country" placeholder="<?php echo $view->l_Name; ?>"></div>
                </div>-->
                
                <div class="mt-5 text-right">
                    <button class="btn btn-primary profile-button" type="submit">Save Profile</button>
                </div>

                <?php if (isset($_GET["updated"]) && $_GET["updated"] == "true"): ?>
                    <div class="d-flex justify-content-center">
                        <div class="alert alert-success mt-3" role="alert">
                            User information successfully updated!
                        </div>
                    </div>
                <?php endif; ?>

            </div>
        </div>
    </div>
</div>
</form>

    
<script src="./js/Profile.js"></script>
    <!--
<div class="container rounded bg-white mt-5">
    <div class="row">
        <div class="col-md-4 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" src="https://i.imgur.com/0eg0aG0.jpg" width="90"><span class="font-weight-bold">John Doe</span><span class="text-black-50">john_doe12@bbb.com</span><span>United States</span></div>
        </div>
        <div class="col-md-8">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <div class="d-flex flex-row align-items-center back"><i class="fa fa-long-arrow-left mr-1 mb-1"></i>
                        <h6>Back to home</h6>
                    </div>
                    <h6 class="text-right">Edit Profile</h6>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><input type="text" class="form-control" placeholder="first name" value="John"></div>
                    <div class="col-md-6"><input type="text" class="form-control" value="Doe" placeholder="Doe"></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6"><input type="text" class="form-control" placeholder="Email" value="john_doe12@bbb.com"></div>
                    <div class="col-md-6"><input type="text" class="form-control" value="+19685969668" placeholder="Phone number"></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6"><input type="text" class="form-control" placeholder="address" value="D-113, right avenue block, CA,USA"></div>
                    <div class="col-md-6"><input type="text" class="form-control" value="USA" placeholder="Country"></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6"><input type="text" class="form-control" placeholder="Bank Name" value="Bank of America"></div>
                    <div class="col-md-6"><input type="text" class="form-control" value="043958409584095" placeholder="Account Number"></div>
                </div>
                <div class="mt-5 text-right"><button class="btn btn-primary profile-button" type="button">Save Profile</button></div>
            </div>
        </div>
    </div>
</div> -->
</body>
</html>

<?php 
require('template/footer.phtml');
?>