<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

require("template/CustomerNavBar.phtml");

?>

<!DOCTYPE html>
<html>
<head>
    <link href="/css/sharedLayout.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Search Charge Points</title>
</head>
<body>
    <main class="manage-container">
        <h2 class="page-title">Search Charge Points</h2>
    </main>
</body>
</html>



<?php
require('template/footer.phtml');
?>