<?php

require('template/header.phtml');

?>

<div class="container px-4 py-5 mx-auto">
    <div class="card card0">
        <div class="d-flex flex-lg-row flex-column-reverse">
            <div class="card card1">
                <div class="row justify-content-center my-auto">
                    <div class="col-md-8 col-10 my-5">
                        <div class="row justify-content-center px-3 mb-3">
                            <img id="mainLogo" src="/images/PowerUpLogo.png" style="width: 100%; height:40px">
                        </div>
                        <h3 class="mb-5 text-center heading">Sign Up for Power Up</h3>

                        <form id="regForm" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
                        <div class="form-group">
                            <label class="form-control-label text-muted">First Name</label>
                            <input type="text" id="fname" name="fname" placeholder="Enter your first name" class="form-control" >
                            <?php if (!empty($view->errors['fname'])): ?>
                                <small class="text-danger"><?php echo htmlspecialchars($view->errors['fname']) ?></small>
                            <?php endif; ?>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label text-muted">Last Name</label>
                            <input type="text" id="lname" name="lname" placeholder="Enter your last name" class="form-control" >
                            <?php if (!empty($view->errors['lname'])): ?>
                                <small class="text-danger"><?php echo htmlspecialchars($view->errors['lname']) ?></small>
                            <?php endif; ?>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label text-muted">Email</label>
                            <input type="text" id="email" name="email" placeholder="Enter your email" class="form-control" >
                            <?php if (!empty($view->errors['email'])): ?>
                                <small class="text-danger"><?php echo htmlspecialchars($view->errors['email']) ?></small>
                            <?php endif; ?>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label text-muted">Password</label>
                            <input type="password" id="password" name="password" placeholder="Enter your password" class="form-control" >
                            <?php if (!empty($view->errors['password'])): ?>
                                <small class="text-danger"><?php echo htmlspecialchars($view->errors['password']) ?></small>
                            <?php endif; ?>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label text-muted">Phone Number</label>
                            <input type="text" id="phno" name="phno" placeholder="Enter your phone number" class="form-control" >
                            <?php if (!empty($view->errors['phno'])): ?>
                                <small class="text-danger"><?php echo htmlspecialchars($view->errors['phno']) ?></small>
                            <?php endif; ?>
                        </div>
                        <!--<div class="form-group">
                            <label class="form-control-label text-muted">Address</label>
                            <input type="text" id="address" name="address" placeholder="Address: D-113, right avenue block, CA,USA" class="form-control" >
                            <?php //if (!empty($view->errors['address'])): ?>
                                <small class="text-danger"><?php //echo htmlspecialchars($view->errors['address']) ?></small>
                            <?php //endif; ?>
                        </div>-->
                            <!-- reCAPTCHA (This will be uncommented once we deploy in the server)-->
                            <!--   <div class="g-recaptcha" data-sitekey="6LdJYD4rAAAAAGZjJjKcu9FqJ1X6BrsZkRg1LaZq"></div>-->
                        <div class="row justify-content-center my-3 px-3">
                            <button type="submit" class="btn-block btn-color">Sign Up to Tidi</button>
                        </div>
                        </form>
                    </div>
                    <?php
                    if (!empty($view->successReg)) { ?>
                        <div class="d-flex justify-content-center">
                            <div class="alert alert-success">
                                <?php echo $view->successReg; ?>
                            </div>
                        </div>
                        <?php
                    }
                    ?>
                </div>
                <div class="bottom text-center mb-5">
                    <p class="sm-text mx-auto mb-3">Register as a Home owner? <button class="btn btn-white ml-2"><a href="/HomeownerRegistration.php">Sign Up</a></button></p>
                </div>
                <div class="bottom text-center mb-5">
                    <p class="sm-text mx-auto mb-3">Already have an account? <button class="btn btn-white ml-2"><a href="/Login.php">Login</a></button></p>
                </div>
            </div>
            <div class="card card2">
                <div class="my-auto mx-md-5 px-md-5 right">
                    <h3 class="text-white text-center">Your place to power up your EV!</h3>
                    <small class="text-white">The future of EV charging is here. Find your nearest charging station and experience the convenience of Power Up.</small>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="module" src="./js/RegistrationFormValidation.js"></script>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<?php

require('template/footer.phtml');

?>

