<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

require('template/header.phtml');

?>
<head>
    <link href="css/LoginRegCSS.css" rel="stylesheet">
</head>


<div class="container px-4 py-5 mx-auto">
    <div class="card card0">
        <div class="d-flex flex-lg-row flex-column-reverse">
            <div class="card card1">
                <div class="row justify-content-center my-auto">
                    <div class="col-md-8 col-10 my-5">
                        <div class="row justify-content-center px-3 mb-3">
                            <img id="logo" src="https://i.imgur.com/PSXxjNY.png">
                        </div>
                        <h3 class="mb-5 text-center heading">Sign Up for Tidi</h3>
                        <div class="form-group">
                            <label class="form-control-label text-muted">First Name</label>
                            <input type="text" id="fname" name="fname" placeholder="Enter your first name" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="form-control-label text-muted">Last Name</label>
                            <input type="text" id="lname" name="lname" placeholder="Enter your last name" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="form-control-label text-muted">Email</label>
                            <input type="text" id="email" name="email" placeholder="Enter your email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="form-control-label text-muted">Phone Number</label>
                            <input type="text" id="phno" name="phno" placeholder="Enter your phone number" class="form-control">
                        </div>
                        <div class="row justify-content-center my-3 px-3">
                            <button class="btn-block btn-color">Sign Up to Tidi</button>
                        </div>
                    </div>
                </div>
                <div class="bottom text-center mb-5">
                    <p href="#" class="sm-text mx-auto mb-3">Already have an account? <button class="btn btn-white ml-2"><a href="Login.php">Login</a></button></p>
                </div>
            </div>
            <div class="card card2">
                <div class="my-auto mx-md-5 px-md-5 right">
                    <h3 class="text-white">We are more than just a company</h3>
                    <small class="text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</small>
                </div>
            </div>
        </div>
    </div>
</div>

<?php

require('template/footer.phtml');

?>