<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

require("template/CustomerNavBar.phtml");

?>

<html>
    <head>
        <link href="/css/sharedLayout.css" rel="stylesheet">
    </head>
    <body>
    <main class="manage-container">
        <h2 class="page-title">Your Booking Requests</h2>



    </main>
    </body>
</html>



<?php
require('template/footer.phtml');
?>