
</body>

<footer>
    <div class="container">
        <p>&copy; 2025 EV Portal. All rights reserved.</p>
    </div>
</footer>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.bundle.min.js"></script>
<script src="js/LoginRegJS.js"></script>
</body>
</html>